# Lazylog Configuration Example
#
# Copy this file to: ~/.config/lazylog/config.toml

# Supported colors: red, green, yellow, blue, magenta, cyan, white, black, gray, lightred, lightgreen, lightyellow, lightblue, lightmagenta, lightcyan

# Highlight inline patterns. If no style is specified, a highlight color is generated.
# Style only applies to the matched part of the line.
highlights = [
    { pattern = "/[\\w/.-]+", regex = true }, # File paths
    { pattern = "\\d+\\.\\d+\\.\\d+\\.\\d+:\\d{2,5}\\b|[a-zA-Z0-9.-]+:\\d{2,5}\\b", regex = true },
    { pattern = "\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}", regex = true },  # IP addresses
    { pattern = "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}", regex = true },  # UUIDs
    { pattern = "order_id" },  # Plain string matching
    { pattern = "FROM", case_sensitive = true },
    { pattern = "\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}", regex = true, style = { fg = "darkgray" } },  # Timestamps (ISO8601)
]

# Event patterns. If no style is specified, a default style is applied (fg=white, bg=lightgreen).
# Style applies to the entire line containing the matched pattern.
# The optional "critical" flag highlights the event in red in the scrollbar and event lists.
# Events are evaluated from top to bottom, and the first match is used.
# Event patterns are case-sensitive.
# Set critical=true to highlight critical events with red markers in scrollbar and event lists.
events = [
    # Log levels events
    { name = "Error",    pattern = " ERROR ",                     regex = false, style = { fg = "lightred", bold = true } },
    { name = "Warning",  pattern = " WARNING ",                   regex = false, style = { fg = "yellow" } },
    { name = "Critical", pattern = " CRITICAL ", critical = true, regex = false, style = { bg = "red" } },
    { name = "Fatal",    pattern = " FATAL ",    critical = true, regex = false, style = { fg = "black", bg = "lightred", bold = true } },
    # Custom events
    { name = "Job Started",         pattern = "Background job started",           regex = false },
    { name = "Application Started", pattern = "Application started successfully", regex = false },
]

# Optional: default event colors
# https://ratatui.rs/examples/style/colors/
default_event_fg_color_index = 255
default_event_bg_color_index = 18
default_custom_event_bg_color_index = 64

# Predefined filters.
filters = [
    { pattern = "DEBUG", mode = "exclude", case_sensitive = false, enabled = true },
    { pattern = "INFO",  mode = "include", case_sensitive = true,  enabled = false },
]
